# Generated by Django 6.1.1 on 2026-09-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True)),
                ('commission_note', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('min_age_months', models.PositiveIntegerField()),
                ('max_age_months', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('age_groups', models.ManyToManyField(blank=True, related_name='articles', to='catalog.agegroup')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('book_type', models.CharField(choices=[('audio', 'صوتی'), ('video', 'تصویری/انیمیشن'), ('text', 'متنی')], max_length=10)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_groups', models.ManyToManyField(related_name='books', to='catalog.agegroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('why_it_helps', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='toys/')),
                ('affiliate_url', models.URLField(blank=True)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.affiliatesource')),
                ('age_groups', models.ManyToManyField(related_name='toys', to='catalog.agegroup')),
                ('development_areas', models.ManyToManyField(blank=True, related_name='toys', to='catalog.developmentarea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
