# Generated by Django 6.1.1 on 2026-09-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('audio', 'ط·آµط¸ث†ط·ع¾ط¸ظ¹'), ('video', 'ط·ع¾ط·آµط¸ث†ط؛إ’ط·آ±ط؛إ’/ط·آ§ط¸â€\xa0ط؛إ’ط¸â€¦ط؛إ’ط·آ´ط¸â€\xa0'), ('text', 'ط¸â€¦ط·ع¾ط¸â€\xa0ط؛إ’')], max_length=10),
        ),
    ]
