# Generated by Django 6.1.1 on 2026-09-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('audio', 'کتاب صوتی'), ('video', 'ویدئو / انیمیشن'), ('text', 'کتاب متنی')], max_length=10),
        ),
    ]
