# Generated by Django 6.1.1 on 2026-09-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_article_source_name_article_source_url_book_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lullaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lullabies/')),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('is_public_domain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_groups', models.ManyToManyField(blank=True, related_name='lullabies', to='catalog.agegroup')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ParentLullabyRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='parent_lullabies/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lullaby_recordings', to='catalog.childprofile')),
                ('lullaby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_recordings', to='catalog.lullaby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lullaby_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
