# Generated by Django 6.1.1 on 2026-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_lullaby_parentlullabyrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='lullaby',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
