# Generated by Django 6.1.1 on 2026-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_lullaby_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='developmental_benefit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='evidence_source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='evidence_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_parent_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='purchase_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
