# Generated by Django 6.1.1 on 2026-09-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_awards_book_developmental_benefit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
