# Generated by Django 6.1.1 on 2026-09-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_book_purchase_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='evidence_source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lullaby',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
