# Generated by Django 6.1.1 on 2026-09-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_article_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='affiliate_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
